var dataLayer=dataLayer||[],gtm_products=gtm_products||[];
(function(e,q,C){dataLayer=e.dataLayer;gtm_products=e.gtm_products;var K=e.location.hostname,D=e.location.pathname,E=e.location.hash,A=!1,x=null,L=e.documentLanguage||"tr",M=-1<q.location.href.indexOf("gadebug"),f=function(){M&&console.log.apply(e.console,arguments)},k=function(a){var b={"\u00e7\u00c7":"c","\u011f\u011e":"g","\u015f\u015e":"s","\u00fc\u00dc":"u","\u0131\u0130":"i","\u00f6\u00d6":"o"};a=a.toString();for(var c in b)a=a.replace(new RegExp("["+c+"]","g"),b[c]);return a.replace(/[^_-a-zA-Z0-9\s]+/ig,
"").replace(/\s/gi,"-").replace(/[-]+/gi,"-").toLowerCase()},h=function(a){dataLayer.push(a)},F=function(){E=e.location.hash;D=e.location.pathname;var a="/haritada-emlak-arama/ localhost banaozel.sahibinden.com /odeme-yap /emlak360/emlak-endeksi /hizmetler /kategori -hizmetleri /anasayfa-vitrin-ozet / /servisler /banaozel-ozet /kategoriler /emlak360 /oto360".split(" "),b=!1,c;for(c in a){var d=a[c];if(-1<K.indexOf(d)||-1<D.indexOf(d)||-1<E.indexOf(d)){b=!0;break}}return b},l=function(a){if(!0===A&&
!1===F())return!1;var b={event:"virtualPageView"};a&&a.charAt&&(a=("/"==a.charAt(0)?"":"/")+a,b.pageView=a);h(b);A=!0},B=function(a,b,c,d,g){null==d&&(d=0);h({Category:a,Action:b,Label:g?c:k(c),Value:d,event:"gaEvent"})},m=function(a,b,c,d){a={};a[b]=c;h(a)},t,u=function(a){return"/"+a.join("/")+"/"},G=function(a,b){if(a){"undefined"!==typeof a.isStore&&b.push(a.isStore?"kurumsal":"bireysel");"undefined"!==typeof a.isGet&&b.push(a.isGet?"get":"ilan");if("undefined"!==typeof a.categories&&null!=a.categories&&
0<a.categories.length)for(b.push("kat"),t=0,length=a.categories.length;t<length;t++)b.push(k(a.categories[t]));"undefined"!==typeof a.isUsed&&null!==a.isUsed&&"null"!==a.isUsed&&b.push(a.isUsed?"ikinci-el":"sifir");if("undefined"!==typeof a.locations&&null!=a.locations&&0<a.locations.length)for(b.push("yer"),t=0,length=a.locations.length;t<length;t++)b.push(k(a.locations[t]))}},N=function(a,b){var c=Date.now,d=e.requestAnimationFrame,g=c(),f,h=function(){c()-g<b||(g+=b,a());f||d(h)};d(h);return{clear:function(){f=
1}}},z={homepage:function(a){a.hasOwnProperty("viewName")&&a.viewName&&(f("homepage generated: "+a.viewName),l(a.viewName))},login:function(a){a.hasOwnProperty("viewName")&&a.viewName&&(f("login generated: "+a.viewName),l(a.viewName))},classified:function(a){f("route \x3d classified");var b=[],c=a.classified;b.push(c.isGet?"get":"ilan");b.push(c.isActive?"aktif":"pasif");b.push(c.isStore?"kurumsal":"bireysel");"undefined"!==typeof c.isUsed&&null!==c.isUsed&&"null"!==c.isUsed&&b.push(c.isUsed?"ikinci-el":
"sifir");b.push("kat");a=0;for(length=c.categories.length;a<length;a++)b.push(k(c.categories[a]));b.push("yer");a=0;for(length=c.locations.length;a<length;a++)b.push(k(c.locations[a]));b=u(b);f("custom classified url generated: "+b);l(b)},postad:function(a){f("route \x3d postad");var b=[],c=a.view;a=a.classified;b.push("ilan-verme");b.push({addclassified1:"kategori",addclassified2:"detay",classified:"onizleme",doping:"doping",addclassified5:"tesekkur"}[c]);G(a,b);b=u(b);f("custom postad url generated: "+
b);a.isSucceed&&h(a.succeedData);l(b)},search:function(a){f("route \x3d search");var b=[],c,d=a.categories,g=a.locations;b.push("arama");a.hasOwnProperty("viewName")&&a.viewName&&"search"!==a.viewName&&b.push(a.viewName);"undefined"!==typeof a.searchResult&&null!==a.searchResult&&"null"!==a.searchResult&&(null!==a.searchResult.isGet&&"null"!==a.searchResult.isGet&&b.push(a.searchResult.isGet?"get":"ilan"),null!==a.searchResult.isUsed&&"null"!==a.searchResult.isUsed&&b.push(a.searchResult.isUsed?"ikinci-el":
"sifir"));if(0<d.length)for(c in b.push("kat"),d)b.push(k(d[c]));if(0<g.length)for(c in b.push("yer"),g)b.push(k(g[c]));b=u(b);a.query&&(b+="?q\x3d"+a.query);f("custom search url generated: "+b);l(b)},category:function(a){f("route \x3d category");var b=[],c;a=a.categories;b.push("kategori");for(c in a)b.push(k(a[c]));b=u(b);f("custom category url generated: "+b);l(b)},store:function(a){f("route \x3d store");var b=[],c,d=a.storeSubdomain.categories;b.push("magaza");b.push({2:"emlak",1:"vasita",3:"alisveris",
5:"is-makinesi",4:"hayvanlar-alemi",7:"hepsi-bir",9:"yedek-parca"}[a.storeSubdomain.packetId]);if(0<d.length)for(c in b.push("kat"),d)b.push(k(d[c]));b=u(b);a.storeSubdomain.query&&(b+="?q\x3d"+a.storeSubdomain.query);f("custom store url generated: "+b);l(b)},payment:function(a){if(a.hasOwnProperty("classified")){var b=[];b.push(a.viewName);classified=a.classified;G(classified,b);a=u(b);f("custom payment url generated: "+a)}else a="/"+a.viewName,f("payment store url generated: "+a);l(a)},register:function(a){f("route \x3d register");
var b={"/kayit/":"/uye-ol/","/eposta-kayit/":"/son-1-adim/"};a=a.view;var c,d;for(d in b)if(-1<d.indexOf(a)){c=b[d];break}else c=a;f("submitted page url: "+c);l(c)},custom:function(a){if(a.hasOwnProperty("viewName")&&a.viewName){var b=[];b.push(a.viewName);url=u(b);f("custom url generated: "+url);l(url)}if(a.hasOwnProperty("trackEvent")&&a.trackEvent)for(var b=0,c=a.trackEvent.length;b<c;b++)B(a.trackEvent[b].category,a.trackEvent[b].action,a.trackEvent[b].label,null,!0)},error:function(a){f("route \x3d error");
a="hata_"+a.errorCode+"_"+q.location.href;f("generated error url: "+a);l(a)}},v=function(a){a=q.cookie.match(new RegExp("(; )?"+a+"\x3d([^;]*);?"));return null!==a&&2<a.length?a[2]:null},n=function(a,b,c){c||(c=new Date,c.setMonth(c.getMonth()+12));q.cookie=a+"\x3d"+b+";expires\x3d"+c+";domain\x3d.sahibinden.com;"},p=function(a){a=a.replace(/[\[]/,"\\[").replace(/[\]]/,"\\]");a=(new RegExp("[\\?\x26]"+a+"\x3d([^\x26#]*)")).exec(location.search);return null==a?"":decodeURIComponent(a[1].replace(/\+/g,
" "))},H=function(){var a=e.pageTrackData,b;if(a&&a.hasOwnProperty("userSegment"))h({"user segment":a.userSegment});else if(b=v("userType"))b=b.replace("_yapi","_ismakineleri"),h({"user segment":b});if(a===C)f("pageTrackData variable couldn't found. tracking url..."),l();else{b=a.route;h({l:L});h({dc:a.dc||""});a.homepageDesign&&h({homepage_design:a.homepageDesign});a.successfulPaymentWithSavedCC&&h({Category:"Funnel",Action:"kayitliOdeme",Label:"tebrikler",Value:0,event:"gaEvent"});if(a.hasOwnProperty("transactionObject")&&
a.transactionObject){if(a.transactionObject.hasOwnProperty("transactionProducts")&&a.transactionObject.transactionProducts&&0<a.transactionObject.transactionProducts.length){var c=0,d=a.transactionObject.transactionProducts,g=d.length;for(c;c<g;c++)gtm_products.push(d[c])}a.transactionObject.transactionProducts=gtm_products;h(a.transactionObject);a.transactionUserItem&&(h({Category:"Transaction",Action:"Loyalty",Label:"Recurrence",Value:a.transactionUserItem.recurrence,event:"gaEvent"}),h({Category:"Transaction",
Action:"Loyalty",Label:"Delay",Value:a.transactionUserItem.delay,event:"gaEvent"}))}var d=q.referrer,c=-1<e.navigator.userAgent.indexOf("EmbeddedBrowser"),d=0<d.length&&c?"WebView \x3e WebView":C,g="Unknown OS",k=navigator.userAgent;-1!==k.indexOf("like Mac")?g="iOS":-1!==k.indexOf("Android")?g="Android":-1!==k.indexOf("Mac")?g="Macintosh":-1!==k.indexOf("Win")?g="Windows":-1!==k.indexOf("Linux")&&(g="Linux");h({os:g,webView:c});d&&h({Category:d,Action:a.view,Label:a.viewName,Value:0,event:"gaEvent"});
if(b in z)z[b](a);else F()||l()}},y="Yepyeni-std";(new RegExp(/nwsh=fct/)).test(q.cookie)&&(y="Yepyeni-fct");m(1,"Arama Menusu",y,2);m(1,"ilan detay","yeni",2);var w=v("MS1"),r=v("MS2"),I=v("MDR"),y="shuid dopingPurchase dopingTotal dopingFrequency lastDopingPurchase lastVisit getPurchase getTotal getFrequency lastGetPurchase".split(" ");if(w)null!==r&&m(1,"MS2",r,2);else{var w=p("gclid"),J=p("utm_source");if(w)w="adwords";else if(J){if(w=J,null===r&&(r=p("utm_campaign")))n("MS2",r),m(1,"MS2",r,2)}else w=
q.referrer;n("MS1",w)}null!==I&&m(1,"MDR",I,2);if(Object.prototype.hasOwnProperty.call(e,"pageTrackData")&&(pageTrackData.hasOwnProperty("view")&&pageTrackData.view&&m(1,"pageType",pageTrackData.view,2),pageTrackData.hasOwnProperty("customVars")&&pageTrackData.customVars))for(n=0;n<pageTrackData.customVars.length;n++)p=pageTrackData.customVars[n],m(1,k(p.name),p.value?p.value:"",2);n=null===v("shuid")?0:1;m(1,"ULS",n,2);for(n=0;n<y.length;n++)p=y[n],r=v(p),null!==r&&m(1,p,r,2);(function(){var a=parseInt(v("vid"),
10)/10;m(1,"bestmatch-alisveris",0<a&&2>a?"a-2":"b-98",2);m(1,"ab-alisveris_sifir_ikinciel",0<a&&50>a?"a-50":"b-50",2)})();(function(a,b,c,d,g){a[d]=a[d]||[];a[d].push({"gtm.start":(new Date).getTime(),event:"gtm.js"});a=b.getElementsByTagName(c)[0];b=b.createElement(c);b.async=!0;b.src="//www.googletagmanager.com/gtm.js?id\x3d"+g+("dataLayer"!=d?"\x26l\x3d"+d:"");a.parentNode.insertBefore(b,a)})(e,q,"script","dataLayer","GTM-58T6ZP");(function(a){var b=N(function(){"complete"===q.readyState&&(a(),
b.clear())},1)})(H);e.gaTrackPageview=l;e.gaReinitializeAndTrackPageview=function(){A=!1;H()};e.gaTrackEvent=B;e.gaTrackEventWithCallback=function(a,b,c,d,g,e){B(a,b,c,d,e);x=function(){g&&g()};setTimeout(x,500)};e.gaHitCallback=function(){x&&(x(),x=null)};e.gaSetCustomVar=m;e.gaAddItem=function(a,b,c,d,g,e){gtm_products.push({sku:b,name:c,category:d,price:g,quantity:e})};e.gaAddTrans=function(a,b,c,d,e,f,k,l){h({transactionId:a,transactionTotal:c,transactionShipping:e,transactionTax:d,transactionProducts:gtm_products,
event:"transaction"})};e.gaTrackTrans=function(){l("_trackTrans")};e.slugify=k;e.gaTrackPostad=z.postad;e.gaTrackPayment=z.payment;e.gaTrackCustomEvent=function(a,b,c,d,e){e=e?e:0;h({Category:b,Action:c,Label:k(d),Value:e,event:a})}})(window,document);